import type { SheEvent } from '@/types';

export const events: SheEvent[] = [
  {
    id: 'evt-1',
    name: 'Sunrise Power Walk & Coffee',
    date: '2025-04-12',
    dateLabel: 'Sat, Apr 12',
    format: 'Movement',
    location: 'Meridian Hill Park, DC',
    image: 'https://images.unsplash.com/photo-1551632811-561732d1e306?w=800&q=80&auto=format&fit=crop',
    description: 'Start your Saturday with movement, fresh air, and fresh perspectives.',
    ctaLabel: 'RSVP',
  },
  {
    id: 'evt-2',
    name: 'Founders Who Pivot: A Panel',
    date: '2025-04-24',
    dateLabel: 'Thu, Apr 24',
    format: 'Panel Discussion',
    location: 'Eaton DC, Washington DC',
    image: 'https://images.unsplash.com/photo-1573164713988-8665fc963095?w=800&q=80&auto=format&fit=crop',
    description: 'Three founders. Three pivots. One unforgettable evening of honest stories.',
    ctaLabel: 'Get Tickets',
  },
  {
    id: 'evt-3',
    name: 'Brand Like You Mean It: A Workshop',
    date: '2025-05-08',
    dateLabel: 'Thu, May 8',
    format: 'Workshop',
    location: 'The Wing, Bethesda MD',
    image: 'https://images.unsplash.com/photo-1591115765373-5207764f72e7?w=800&q=80&auto=format&fit=crop',
    description: 'A hands-on session to clarify your voice, your visuals, and your value.',
    ctaLabel: 'Get Tickets',
  },
  {
    id: 'evt-4',
    name: 'Founders Table: An Intimate Dinner',
    date: '2025-05-22',
    dateLabel: 'Thu, May 22',
    format: 'Founder Gathering',
    location: 'Private Residence, Arlington VA',
    image: 'https://images.unsplash.com/photo-1529543544282-ea669407fca3?w=800&q=80&auto=format&fit=crop',
    description: 'A curated evening of 10 founders, honest conversation, and beautiful food.',
    ctaLabel: 'RSVP',
  },
  {
    id: 'evt-5',
    name: 'Yoga + Journaling Reset',
    date: '2025-06-07',
    dateLabel: 'Sat, Jun 7',
    format: 'Movement',
    location: 'Rock Creek Park, DC',
    image: 'https://images.unsplash.com/photo-1545389336-cf090694435e?w=800&q=80&auto=format&fit=crop',
    description: 'Flow, breathe, and write your way back to yourself.',
    ctaLabel: 'RSVP',
  },
  {
    id: 'evt-6',
    name: 'Money Moves: A Finance Workshop',
    date: '2025-06-19',
    dateLabel: 'Thu, Jun 19',
    format: 'Workshop',
    location: 'WeWork Tysons, VA',
    image: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=800&q=80&auto=format&fit=crop',
    description: 'Practical, no-shame strategies to build wealth on your own terms.',
    ctaLabel: 'Get Tickets',
  },
];
